#!/usr/bin/env node
/** Generate crawler rules and security headers for the selected build. */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const publicDir = join(root, "public");
const isProduction = (process.env.SITE_ENV ?? "").toLowerCase() === "production";
const stamp = `# GENERATED by scripts/prepare-env.mjs — do not edit by hand.\n# SITE_ENV=${isProduction ? "production" : "staging"}\n`;

function siteUrl() {
  if (process.env.SITE_URL) return process.env.SITE_URL.replace(/\/$/, "");
  try {
    const config = readFileSync(join(root, "astro.config.mjs"), "utf8");
    const match = config.match(/site:\s*["'`]([^"'`]+)["'`]/);
    return match ? match[1].replace(/\/$/, "") : "";
  } catch {
    return "";
  }
}

const canonical = siteUrl();
const robots = isProduction
  ? `${stamp}\n# Search-engine and AI crawlers are permitted.\nUser-agent: *\nAllow: /\n${canonical ? `\nSitemap: ${canonical}/sitemap-index.xml\n` : ""}`
  : `${stamp}\nUser-agent: *\nDisallow: /\n`;

const headers = isProduction
  ? `${stamp}\n/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n`
  : `${stamp}\n/*\n  X-Robots-Tag: noindex, nofollow, noarchive\n  X-Content-Type-Options: nosniff\n`;

writeFileSync(join(publicDir, "robots.txt"), robots);
writeFileSync(join(publicDir, "_headers"), headers);
console.log(`prepare-env — wrote robots.txt and _headers for ${isProduction ? "PRODUCTION" : "STAGING"}`);
